use std::{
    fs::File,
    io::{BufRead, BufReader, BufWriter, Write},
    path::Path,
};

use cantools_core::{
    CanFrame, CanId, CaptureEvent, Direction, FdFlags, FrameClass, InterfaceRef, Timestamp,
};

use crate::{CodecError, FidelityNote, ReadReport, Result, WriteReport};

fn direction_from_str(raw: &str) -> Option<Direction> {
    match raw {
        "Rx" => Some(Direction::Rx),
        "Tx" => Some(Direction::Tx),
        _ => None,
    }
}

fn encode_hex_bytes(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|byte| format!("{byte:02X}"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn parse_hex_id(raw: &str) -> Result<(CanId, bool)> {
    let trimmed = raw.trim_end_matches('x');
    let extended = raw.ends_with('x') || trimmed.len() > 3;
    let value = u32::from_str_radix(trimmed, 16)
        .map_err(|error| CodecError::Parse(format!("invalid ASC identifier {raw}: {error}")))?;
    let id = if extended {
        CanId::extended(value)?
    } else {
        CanId::standard(value as u16)?
    };
    Ok((id, extended))
}

/// Read an ASC log into capture events.
pub fn read_asc(path: &Path) -> Result<ReadReport> {
    let file = File::open(path)?;
    let reader = BufReader::new(file);
    let mut notes = Vec::new();
    let mut events = Vec::new();

    for line in reader.lines() {
        let line = line?;
        let trimmed = line.trim();
        if trimmed.is_empty()
            || trimmed.starts_with("date")
            || trimmed.starts_with("base")
            || trimmed.starts_with("Begin Triggerblock")
            || trimmed.starts_with("End TriggerBlock")
            || trimmed.starts_with("//")
        {
            continue;
        }

        let parts = trimmed.split_whitespace().collect::<Vec<_>>();
        if parts.len() < 6 {
            notes.push(FidelityNote {
                event_index: None,
                field: "line",
                detail: format!("skipped unrecognized ASC line: {trimmed}"),
            });
            continue;
        }

        let seconds = parts[0].parse::<f64>().map_err(|error| {
            CodecError::Parse(format!("invalid ASC timestamp {}: {error}", parts[0]))
        })?;
        let interface = InterfaceRef {
            name: Some(parts[1].to_string()),
            index: None,
        };
        let (id, _) = parse_hex_id(parts[2])?;
        let direction = direction_from_str(parts[3])
            .ok_or_else(|| CodecError::Parse(format!("invalid ASC direction {}", parts[3])))?;
        let frame_kind = parts[4];

        let data = if frame_kind.eq_ignore_ascii_case("d") || frame_kind.eq_ignore_ascii_case("fd")
        {
            let declared_len = parts[5].parse::<usize>().map_err(|error| {
                CodecError::Parse(format!("invalid ASC dlc {}: {error}", parts[5]))
            })?;
            let mut bytes = Vec::new();
            for token in parts.iter().skip(6).take(declared_len) {
                let byte = u8::from_str_radix(token, 16).map_err(|error| {
                    CodecError::Parse(format!("invalid ASC data byte {token}: {error}"))
                })?;
                bytes.push(byte);
            }
            bytes
        } else {
            Vec::new()
        };

        let fd = frame_kind.eq_ignore_ascii_case("fd");
        let class = if frame_kind.eq_ignore_ascii_case("r") {
            FrameClass::Remote
        } else if frame_kind.eq_ignore_ascii_case("error") {
            FrameClass::Error
        } else {
            FrameClass::Data
        };

        let nanos_total = (seconds * 1_000_000_000.0).round() as i64;
        let timestamp = Timestamp {
            seconds: nanos_total / 1_000_000_000,
            nanos: (nanos_total.rem_euclid(1_000_000_000)) as u32,
        };
        let frame = CanFrame::new(id, class, data, fd, FdFlags::default())?;
        events.push(CaptureEvent::new(timestamp, interface, direction, frame));
    }

    Ok(ReadReport { events, notes })
}

/// Write capture events to an ASC log.
pub fn write_asc(path: &Path, events: &[CaptureEvent]) -> Result<WriteReport> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);
    let mut notes = Vec::new();

    writeln!(writer, "date generated by cantools-rs")?;
    writeln!(writer, "base hex  timestamps absolute")?;
    writeln!(writer, "Begin Triggerblock")?;

    for (index, event) in events.iter().enumerate() {
        if !event.annotations.is_empty() {
            notes.push(FidelityNote {
                event_index: Some(index),
                field: "annotations",
                detail: "ASC cannot persist structured annotations; annotations were omitted"
                    .to_string(),
            });
        }
        if event.interface.index.is_some() {
            notes.push(FidelityNote {
                event_index: Some(index),
                field: "interface_index",
                detail: "ASC does not preserve numeric interface indices; only the interface name was written".to_string(),
            });
        }

        let timestamp =
            event.timestamp.seconds as f64 + f64::from(event.timestamp.nanos) / 1_000_000_000.0;
        let interface = event.interface.name.as_deref().unwrap_or("can0");
        let id = if event.frame.id.is_extended() {
            format!("{:08X}x", event.frame.id.raw())
        } else {
            format!("{:03X}", event.frame.id.raw())
        };
        let direction = match event.direction {
            Direction::Rx => "Rx",
            Direction::Tx => "Tx",
        };
        let kind = match event.frame.class {
            FrameClass::Data if event.frame.fd => "FD",
            FrameClass::Data => "d",
            FrameClass::Remote => "r",
            FrameClass::Error => {
                notes.push(FidelityNote {
                    event_index: Some(index),
                    field: "frame_class",
                    detail: "ASC export downgrades error frames into comment lines".to_string(),
                });
                writeln!(writer, "// error frame {} {}", id, direction)?;
                continue;
            }
        };

        writeln!(
            writer,
            "{timestamp:>10.6} {interface} {id} {direction} {kind} {} {}",
            event.frame.data.len(),
            encode_hex_bytes(&event.frame.data),
        )?;
    }

    writeln!(writer, "End TriggerBlock")?;
    writer.flush()?;
    Ok(WriteReport { notes })
}

#[cfg(test)]
mod tests {
    use std::{fs, path::PathBuf};

    use cantools_core::{
        CanFrame, CanId, CaptureEvent, Direction, FdFlags, FrameClass, InterfaceRef, Timestamp,
    };

    use super::{read_asc, write_asc};

    fn temp_file(name: &str) -> PathBuf {
        std::env::temp_dir().join(name)
    }

    #[test]
    fn asc_round_trip() {
        let path = temp_file("cantools-codec-roundtrip.asc");
        let event = CaptureEvent::new(
            Timestamp {
                seconds: 1,
                nanos: 0,
            },
            InterfaceRef {
                name: Some("vcan0".to_string()),
                index: Some(1),
            },
            Direction::Rx,
            CanFrame::new(
                CanId::standard(0x123).expect("id"),
                FrameClass::Data,
                vec![0x11, 0x22, 0x33],
                false,
                FdFlags::default(),
            )
            .expect("frame"),
        );

        let report = write_asc(&path, std::slice::from_ref(&event)).expect("write asc");
        assert_eq!(report.notes.len(), 1);
        let report = read_asc(&path).expect("read asc");
        fs::remove_file(&path).ok();

        assert_eq!(report.events.len(), 1);
        assert_eq!(report.events[0].timestamp, event.timestamp);
        assert_eq!(report.events[0].interface.name, event.interface.name);
        assert_eq!(report.events[0].frame, event.frame);
    }
}
